#  Copyright (C) 2018 Curt Brune <curt@cumulusnetworks.com>
#  Copyright (C) 2020 Francois Chouinard <frch@kaloom.com>
#
#  Modified with permission from Benayak Karki
#  Added build user/group IDs as arguments
#
#  SPDX-License-Identifier:     GPL-2.0

FROM debian:9

# Add initial development packages
RUN apt-get update && apt-get install -y \
    build-essential stgit u-boot-tools util-linux \
    gperf device-tree-compiler python-all-dev xorriso \
    autoconf automake bison flex texinfo libtool libtool-bin \
    realpath gawk libncurses5 libncurses5-dev bc \
    dosfstools mtools pkg-config git wget help2man libexpat1 \
    libexpat1-dev fakeroot python-sphinx rst2pdf \
    libefivar-dev libnss3-tools libnss3-dev libpopt-dev \
    libssl-dev sbsigntool uuid-runtime uuid-dev cpio \
    bsdmainutils curl sudo

# Create build user
ARG BUILD_GROUP_ID
RUN groupadd -g ${BUILD_GROUP_ID} build
ARG BUILD_USER_ID
RUN useradd -m -u ${BUILD_USER_ID} -g ${BUILD_GROUP_ID} -s /bin/bash build && \
        adduser build sudo && \
        echo "build:build" | chpasswd

WORKDIR /home/build

# Add /sbin and /usr/sbin to build user's path
RUN echo export PATH="/sbin:/usr/sbin:\$PATH" >> .bashrc

# Add common files, like .gitconfig
COPY home .

# Create /home/build/src as a mount point for sharing files with the
# host system.
RUN mkdir src

# Make sure everything in /home/build is owned by the build user
RUN chown -R build:build .

USER build

CMD ["/bin/bash", "--login"]
